version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.4
  # Use temporary dev version in order to make use of
  # the new features of the dev orb
  orb-tools: circleci/orb-tools@dev:newworkflow
  orb-tools-alpha: circleci/orb-tools@<<pipeline.parameters.dev-orb-version>>
  queue: eddiewebb/queue@1.1.2

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

commands:
  check-pr-message:
    parameters:
      orb-name:
        type: string
    steps:
      - run:
          name: Check PR message
          command: |
            echo $PR_MESSAGE
            echo $PR_MESSAGE | grep -e "orb available for use.*<<parameters.orb-name>>"
jobs:
  test-commands:
    parameters:
      executor:
        type: executor

      segment:
        description: >
          The semver segment to increment 'major' or 'minor' or 'patch'
        type: enum
        enum: [major, minor, patch]
        default: patch

    executor: <<parameters.executor>>

    steps:
      - checkout

      - cli/install

      - orb-tools-alpha/install-bats
      - orb-tools-alpha/pack
      - orb-tools-alpha/validate

      - orb-tools-alpha/check-env-var-param:
          command-name: Test `check-env-var-param` command with built-in env vars
          param: CIRCLE_BUILD_NUM,CIRCLE_BRANCH,CIRCLE_BUILD_URL,CIRCLE_JOB

      - orb-tools-alpha/publish:
          orb-ref: sandbox/orb-tools@dev:${CIRCLE_SHA1:0:7}

      - orb-tools-alpha/increment:
          orb-ref: sandbox/orb-tools
          segment: <<parameters.segment>>

  test-promote-from-commit-subject:
    parameters:
      executor:
        type: executor

      segment:
        description: >
          The semver segment to increment 'major' or 'minor' or 'patch'
        type: enum
        enum: [major, minor, patch, skip]
        default: patch

    executor: <<parameters.executor>>

    steps:
      - checkout
      - cli/install
      - orb-tools-alpha/configure-git
      - run:
          name: Set up test repository
          command: |
            cd ..
            rm -rf project
            mkdir project
            cd project
            git init
            echo "test" > test
            git add . && git commit -am "Merge pull request #99TEST from dummy-branch [semver:<<parameters.segment>>]"
      - orb-tools-alpha/dev-promote-from-commit-subject:
          checkout: false
          dev-version: sandbox/orb-tools@dev:${CIRCLE_SHA1:0:7}
          add-pr-comment: true
          bot-user: cpe-bot
          bot-token-variable: GHI_TOKEN
          pr-number-sed-expression: 's/Merge pull request #\([0-9]*TEST\) from.*/\1/p'
      - check-pr-message:
          orb-name: sandbox/orb-tools

  test-promote-from-git-tag:
    parameters:
      executor:
        type: executor

      segment:
        description: >
          The semver segment to increment 'major' or 'minor' or 'patch'
        type: enum
        enum: [major, minor, patch]
        default: patch

    executor: <<parameters.executor>>

    steps:
      - cli/install
      - checkout
      - run:
          name: Mock the built-in CIRCLE_TAG environment variable
          command: |
            echo "export CIRCLE_TAG=\"<<parameters.segment>>-release-v1\"" >> $BASH_ENV
      - orb-tools-alpha/dev-promote-from-git-tag:
          checkout: false
          orb-name: sandbox/orb-tools
          add-pr-comment: true
          bot-user: cpe-bot
          bot-token-variable: GHI_TOKEN
          required-branch: $CIRCLE_BRANCH
      - check-pr-message:
          orb-name: sandbox/orb-tools

# yaml anchor filters
prod-deploy_requires: &prod-deploy_requires
  [
    test-promote-from-git-tag
  ]

requires_commands: &requires_commands
  [
    test-commands-alpine,
    test-commands-machine,
    test-commands-macos,
    test-commands-node-cci,
    test-commands-node,
    test-commands-ubuntu
  ]

orb_promotion_filters: &orb_promotion_filters
  branches:
    ignore: /.*/
  tags:
    only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/

workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint:
          use-default-rules: false

      - orb-tools/pack:
          source-dir: src
          destination-orb-path: orb.yml
          workspace-path: orb.yml
          artifact-path: orb.yml
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: circleci/orb-tools
          requires: [orb-tools/pack]

      - queue/block_workflow:
          requires: [orb-tools/publish-dev]

      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration
          context: orb-publishing
          requires: [queue/block_workflow]

  integration_tests-prod_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # test commands with executors
      - test-commands:
          name: test-commands-alpine
          executor: orb-tools-alpha/alpine
          context: orb-publishing

      - test-commands:
          name: test-commands-machine
          executor: orb-tools-alpha/machine
          context: orb-publishing
          # pre-steps: [run: sleep 2]
          segment: minor

      - test-commands:
          name: test-commands-macos
          executor: orb-tools-alpha/macos
          context: orb-publishing
          # pre-steps: [run: sleep 4]
          segment: major

      - test-commands:
          name: test-commands-node-cci
          executor: orb-tools-alpha/node-cci
          context: orb-publishing
          pre-steps: [run: sleep 2]

      - test-commands:
          name: test-commands-node
          executor: orb-tools-alpha/node
          context: orb-publishing
          pre-steps: [run: sleep 2]
          segment: minor

      - test-commands:
          name: test-commands-ubuntu
          executor: orb-tools-alpha/ubuntu
          context: orb-publishing
          pre-steps: [run: sleep 2]
          segment: major

      # test jobs
      - orb-tools-alpha/pack:
          name: test-pack-job
          workspace-path: orb.yml
          artifact-path: orb.yml
          requires: *requires_commands

      - orb-tools-alpha/test-in-builds:
          name: test-in-builds-job
          context: orb-publishing
          attach-workspace: true
          orb-name: orb-tools-alpha
          requires: [test-pack-job]
          test-steps:
            - checkout

            - orb-tools-alpha/install-bats
            - orb-tools-alpha/pack
            - orb-tools-alpha/validate

            - orb-tools-alpha/publish:
                orb-ref: sandbox/orb-tools@dev:${CIRCLE_SHA1:0:7}

            - orb-tools-alpha/increment:
                orb-ref: sandbox/orb-tools

      - orb-tools-alpha/publish:
          name: test-publish-job
          attach-workspace: true
          context: orb-publishing
          orb-ref: sandbox/orb-tools@dev:${CIRCLE_SHA1:0:7}
          requires: [test-pack-job]

      - orb-tools-alpha/increment:
          name: test-increment-job
          attach-workspace: true
          context: orb-publishing
          orb-ref: sandbox/orb-tools
          requires:
            - test-in-builds-job
            - test-publish-job

      - test-promote-from-commit-subject:
          executor: orb-tools-alpha/ubuntu
          segment: patch
          context: orb-publishing
          requires:
            - test-increment-job

      - test-promote-from-git-tag:
          executor: orb-tools-alpha/ubuntu
          segment: patch
          context: orb-publishing
          requires:
            - test-promote-from-commit-subject

      # semver publishing
      - orb-tools/dev-promote-prod-from-commit-subject:
          name: dev-promote-semver
          add-pr-comment: true
          bot-user: cpe-bot
          bot-token-variable: GHI_TOKEN
          context: orb-publishing
          orb-name: circleci/orb-tools
          ssh-fingerprints: 33:d9:6e:a7:b2:ba:eb:90:7b:7a:dc:90:36:e1:b6:e0
          requires: *prod-deploy_requires
          filters:
            branches:
              only: master

  # Tag-triggered workflow to promote a dev orb into production.
  # The tag is expected to have been applied manually.
  tag-triggered-orb-publishing:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - hold-for-approval:
          type: approval
          filters: *orb_promotion_filters
      - orb-tools/dev-promote-prod-from-git-tag:
          orb-name: sandbox/orb-tools
          #orb-name: circleci/orb-tools
          context: orb-publishing
          add-pr-comment: true
          bot-user: cpe-bot
          bot-token-variable: GHI_TOKEN
          requires:
            - hold-for-approval
          filters: *orb_promotion_filters
